// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripWise.Models;

#nullable disable

namespace TripWise.Migrations
{
    [DbContext(typeof(TripWiseContext))]
    partial class TripWiseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripWise.Models.ChatMessage", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMessage");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMessage"));

                    b.Property<int?>("IdPoint")
                        .HasColumnType("int")
                        .HasColumnName("idPoint");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sentAt");

                    b.HasKey("IdMessage");

                    b.HasIndex(new[] { "IdPoint" }, "IX_ChatMessages_idPoint");

                    b.HasIndex(new[] { "IdTrip" }, "IX_ChatMessages_idTrip");

                    b.HasIndex(new[] { "IdUser" }, "IX_ChatMessages_idUser");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("TripWise.Models.Document", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDocument");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocument"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fileName");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("filePath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fileType");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploadedAt");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int")
                        .HasColumnName("uploadedById");

                    b.HasKey("IdDocument");

                    b.HasIndex(new[] { "IdTrip" }, "IX_Documents_idTrip");

                    b.HasIndex(new[] { "UploadedById" }, "IX_Documents_uploadedById");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TripWise.Models.Expense", b =>
                {
                    b.Property<int>("IdExpense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idExpense");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExpense"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expenseDate");

                    b.Property<int>("IdExpenseCategory")
                        .HasColumnType("int")
                        .HasColumnName("idExpenseCategory");

                    b.Property<int?>("IdPoint")
                        .HasColumnType("int")
                        .HasColumnName("idPoint");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.Property<int?>("PaidById")
                        .HasColumnType("int")
                        .HasColumnName("paidById");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("IdExpense");

                    b.HasIndex("IdExpenseCategory");

                    b.HasIndex(new[] { "IdPoint" }, "IX_Expenses_idPoint");

                    b.HasIndex(new[] { "IdTrip" }, "IX_Expenses_idTrip");

                    b.HasIndex(new[] { "PaidById" }, "IX_Expenses_paidById");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TripWise.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("IdExpenseCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idExpenseCategory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExpenseCategory"));

                    b.Property<string>("ExpenseCategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdExpenseCategory");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("TripWise.Models.ExpenseShare", b =>
                {
                    b.Property<int>("IdExpenseShare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idExpenseShare");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExpenseShare"));

                    b.Property<int>("IdExpense")
                        .HasColumnType("int")
                        .HasColumnName("idExpense");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("isPaid");

                    b.Property<decimal>("ShareAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("shareAmount");

                    b.HasKey("IdExpenseShare");

                    b.HasIndex(new[] { "IdExpense" }, "IX_ExpenseShares_idExpense");

                    b.HasIndex(new[] { "IdUser" }, "IX_ExpenseShares_idUser");

                    b.ToTable("ExpenseShares");
                });

            modelBuilder.Entity("TripWise.Models.FavoriteFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AddedDate");

                    b.Property<string>("Aircraft")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Aircraft");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Airline");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AirlineCode");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ArrivalAirport");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ArrivalCity");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ArrivalTime");

                    b.Property<string>("BookingUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BookingUrl");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("RUB")
                        .HasColumnName("Currency");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DepartureAirport");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DepartureCity");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DepartureTime");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("Duration");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FlightId");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FlightNumber");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("bit")
                        .HasColumnName("IsReturn");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Notes");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("SearchParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SearchParameters");

                    b.Property<int>("Transfers")
                        .HasColumnType("int")
                        .HasColumnName("Transfers");

                    b.Property<DateTime?>("TripDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TripDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FlightId")
                        .IsUnique();

                    b.HasIndex(new[] { "FlightId" }, "IX_FavoriteFlights_FlightId");

                    b.HasIndex(new[] { "UserId" }, "IX_FavoriteFlights_UserId");

                    b.ToTable("FavoriteFlights");
                });

            modelBuilder.Entity("TripWise.Models.InterestCategory", b =>
                {
                    b.Property<int>("IdInterestCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idInterestCategory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInterestCategory"));

                    b.Property<string>("InterestCategory1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("InterestCategory");

                    b.HasKey("IdInterestCategory");

                    b.ToTable("InterestCategories");
                });

            modelBuilder.Entity("TripWise.Models.ParticipantRole", b =>
                {
                    b.Property<int>("IdParticipantRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idParticipantRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParticipantRole"));

                    b.Property<string>("ParticipantRole1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ParticipantRole");

                    b.HasKey("IdParticipantRole");

                    b.ToTable("ParticipantRoles");
                });

            modelBuilder.Entity("TripWise.Models.PointsOfInterest", b =>
                {
                    b.Property<int>("IdPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPoint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPoint"));

                    b.Property<int?>("AddedById")
                        .HasColumnType("int")
                        .HasColumnName("addedById");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("BookingLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("bookingLink");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdInterestCategory")
                        .HasColumnType("int")
                        .HasColumnName("idInterestCategory");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("plannedDate");

                    b.Property<TimeOnly?>("PlannedTime")
                        .HasColumnType("time")
                        .HasColumnName("plannedTime");

                    b.HasKey("IdPoint");

                    b.HasIndex("IdInterestCategory");

                    b.HasIndex(new[] { "AddedById" }, "IX_PointsOfInterest_addedById");

                    b.HasIndex(new[] { "IdTrip" }, "IX_PointsOfInterest_idTrip");

                    b.ToTable("PointsOfInterest", (string)null);
                });

            modelBuilder.Entity("TripWise.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TripWise.Models.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrip"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("createdById");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("endDate");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("totalBudget");

                    b.HasKey("IdTrip");

                    b.HasIndex(new[] { "CreatedById" }, "IX_Trips_createdById");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TripWise.Models.TripParticipant", b =>
                {
                    b.Property<int>("IdTripParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTripParticipant");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTripParticipant"));

                    b.Property<int>("IdParticipantRole")
                        .HasColumnType("int")
                        .HasColumnName("idParticipantRole");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("joinedAt");

                    b.HasKey("IdTripParticipant");

                    b.HasIndex("IdParticipantRole");

                    b.HasIndex(new[] { "IdTrip" }, "IX_TripParticipants_idTrip");

                    b.HasIndex(new[] { "IdUser" }, "IX_TripParticipants_idUser");

                    b.ToTable("TripParticipants");
                });

            modelBuilder.Entity("TripWise.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passwordHash");

                    b.HasKey("IdUser");

                    b.HasIndex(new[] { "IdRole" }, "IX_Users_idRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TripWise.Models.UserVote", b =>
                {
                    b.Property<int>("IdUserVote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUserVote");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserVote"));

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<int>("IdVoteOption")
                        .HasColumnType("int")
                        .HasColumnName("idVoteOption");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("votedAt");

                    b.HasKey("IdUserVote");

                    b.HasIndex(new[] { "IdUser" }, "IX_UserVotes_idUser");

                    b.HasIndex(new[] { "IdVoteOption" }, "IX_UserVotes_idVoteOption");

                    b.ToTable("UserVotes");
                });

            modelBuilder.Entity("TripWise.Models.VoteOption", b =>
                {
                    b.Property<int>("IdVoteOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVoteOption");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVoteOption"));

                    b.Property<int>("IdVote")
                        .HasColumnType("int")
                        .HasColumnName("idVote");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("optionText");

                    b.HasKey("IdVoteOption");

                    b.HasIndex(new[] { "IdVote" }, "IX_VoteOptions_idVote");

                    b.ToTable("VoteOptions");
                });

            modelBuilder.Entity("TripWise.Models.VotingSystem", b =>
                {
                    b.Property<int>("IdVote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVote"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("createdById");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiresAt");

                    b.Property<int?>("IdPoint")
                        .HasColumnType("int")
                        .HasColumnName("idPoint");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("question");

                    b.HasKey("IdVote");

                    b.HasIndex(new[] { "CreatedById" }, "IX_votingSystems_createdById");

                    b.HasIndex(new[] { "IdPoint" }, "IX_votingSystems_idPoint");

                    b.HasIndex(new[] { "IdTrip" }, "IX_votingSystems_idTrip");

                    b.ToTable("votingSystems", (string)null);
                });

            modelBuilder.Entity("TripWise.Models.ChatMessage", b =>
                {
                    b.HasOne("TripWise.Models.PointsOfInterest", "IdPointNavigation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("IdPoint");

                    b.HasOne("TripWise.Models.Trip", "IdTripNavigation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.User", "IdUserNavigation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPointNavigation");

                    b.Navigation("IdTripNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TripWise.Models.Document", b =>
                {
                    b.HasOne("TripWise.Models.Trip", "IdTripNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.User", "UploadedBy")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedById")
                        .IsRequired();

                    b.Navigation("IdTripNavigation");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("TripWise.Models.Expense", b =>
                {
                    b.HasOne("TripWise.Models.ExpenseCategory", "IdExpenseCategoryNavigation")
                        .WithMany("Expenses")
                        .HasForeignKey("IdExpenseCategory")
                        .IsRequired()
                        .HasConstraintName("FK_Expenses_ExpenseCategories");

                    b.HasOne("TripWise.Models.PointsOfInterest", "IdPointNavigation")
                        .WithMany("Expenses")
                        .HasForeignKey("IdPoint");

                    b.HasOne("TripWise.Models.Trip", "IdTripNavigation")
                        .WithMany("Expenses")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.User", "PaidBy")
                        .WithMany("Expenses")
                        .HasForeignKey("PaidById");

                    b.Navigation("IdExpenseCategoryNavigation");

                    b.Navigation("IdPointNavigation");

                    b.Navigation("IdTripNavigation");

                    b.Navigation("PaidBy");
                });

            modelBuilder.Entity("TripWise.Models.ExpenseShare", b =>
                {
                    b.HasOne("TripWise.Models.Expense", "IdExpenseNavigation")
                        .WithMany("ExpenseShares")
                        .HasForeignKey("IdExpense")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.User", "IdUserNavigation")
                        .WithMany("ExpenseShares")
                        .HasForeignKey("IdUser")
                        .IsRequired();

                    b.Navigation("IdExpenseNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TripWise.Models.FavoriteFlight", b =>
                {
                    b.HasOne("TripWise.Models.User", "User")
                        .WithMany("FavoriteFlights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripWise.Models.PointsOfInterest", b =>
                {
                    b.HasOne("TripWise.Models.User", "AddedBy")
                        .WithMany("PointsOfInterests")
                        .HasForeignKey("AddedById");

                    b.HasOne("TripWise.Models.InterestCategory", "IdInterestCategoryNavigation")
                        .WithMany("PointsOfInterests")
                        .HasForeignKey("IdInterestCategory")
                        .IsRequired()
                        .HasConstraintName("FK_PointsOfInterest_InterestCategories");

                    b.HasOne("TripWise.Models.Trip", "IdTripNavigation")
                        .WithMany("PointsOfInterests")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("IdInterestCategoryNavigation");

                    b.Navigation("IdTripNavigation");
                });

            modelBuilder.Entity("TripWise.Models.Trip", b =>
                {
                    b.HasOne("TripWise.Models.User", "CreatedBy")
                        .WithMany("Trips")
                        .HasForeignKey("CreatedById")
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TripWise.Models.TripParticipant", b =>
                {
                    b.HasOne("TripWise.Models.ParticipantRole", "IdParticipantRoleNavigation")
                        .WithMany("TripParticipants")
                        .HasForeignKey("IdParticipantRole")
                        .IsRequired()
                        .HasConstraintName("FK_TripParticipants_ParticipantRoles");

                    b.HasOne("TripWise.Models.Trip", "IdTripNavigation")
                        .WithMany("TripParticipants")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.User", "IdUserNavigation")
                        .WithMany("TripParticipants")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdParticipantRoleNavigation");

                    b.Navigation("IdTripNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("TripWise.Models.User", b =>
                {
                    b.HasOne("TripWise.Models.Role", "IdRoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("TripWise.Models.UserVote", b =>
                {
                    b.HasOne("TripWise.Models.User", "IdUserNavigation")
                        .WithMany("UserVotes")
                        .HasForeignKey("IdUser")
                        .IsRequired();

                    b.HasOne("TripWise.Models.VoteOption", "IdVoteOptionNavigation")
                        .WithMany("UserVotes")
                        .HasForeignKey("IdVoteOption")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUserNavigation");

                    b.Navigation("IdVoteOptionNavigation");
                });

            modelBuilder.Entity("TripWise.Models.VoteOption", b =>
                {
                    b.HasOne("TripWise.Models.VotingSystem", "IdVoteNavigation")
                        .WithMany("VoteOptions")
                        .HasForeignKey("IdVote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdVoteNavigation");
                });

            modelBuilder.Entity("TripWise.Models.VotingSystem", b =>
                {
                    b.HasOne("TripWise.Models.User", "CreatedBy")
                        .WithMany("VotingSystems")
                        .HasForeignKey("CreatedById")
                        .IsRequired();

                    b.HasOne("TripWise.Models.PointsOfInterest", "IdPointNavigation")
                        .WithMany("VotingSystems")
                        .HasForeignKey("IdPoint");

                    b.HasOne("TripWise.Models.Trip", "IdTripNavigation")
                        .WithMany("VotingSystems")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("IdPointNavigation");

                    b.Navigation("IdTripNavigation");
                });

            modelBuilder.Entity("TripWise.Models.Expense", b =>
                {
                    b.Navigation("ExpenseShares");
                });

            modelBuilder.Entity("TripWise.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("TripWise.Models.InterestCategory", b =>
                {
                    b.Navigation("PointsOfInterests");
                });

            modelBuilder.Entity("TripWise.Models.ParticipantRole", b =>
                {
                    b.Navigation("TripParticipants");
                });

            modelBuilder.Entity("TripWise.Models.PointsOfInterest", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Expenses");

                    b.Navigation("VotingSystems");
                });

            modelBuilder.Entity("TripWise.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripWise.Models.Trip", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Documents");

                    b.Navigation("Expenses");

                    b.Navigation("PointsOfInterests");

                    b.Navigation("TripParticipants");

                    b.Navigation("VotingSystems");
                });

            modelBuilder.Entity("TripWise.Models.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Documents");

                    b.Navigation("ExpenseShares");

                    b.Navigation("Expenses");

                    b.Navigation("FavoriteFlights");

                    b.Navigation("PointsOfInterests");

                    b.Navigation("TripParticipants");

                    b.Navigation("Trips");

                    b.Navigation("UserVotes");

                    b.Navigation("VotingSystems");
                });

            modelBuilder.Entity("TripWise.Models.VoteOption", b =>
                {
                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("TripWise.Models.VotingSystem", b =>
                {
                    b.Navigation("VoteOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
