// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripWise.Data;

#nullable disable

namespace TripWise.Migrations
{
    [DbContext(typeof(TripWiseDbContext))]
    partial class TripWiseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripWise.Models.chatMessage", b =>
                {
                    b.Property<int>("idMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMessage"));

                    b.Property<int?>("idPoint")
                        .HasColumnType("int");

                    b.Property<int>("idTrip")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("idMessage");

                    b.HasIndex("idPoint");

                    b.HasIndex("idTrip");

                    b.HasIndex("idUser");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("TripWise.Models.document", b =>
                {
                    b.Property<int>("idDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDocument"));

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("fileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("filePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("fileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("idTrip")
                        .HasColumnType("int");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("uploadedById")
                        .HasColumnType("int");

                    b.HasKey("idDocument");

                    b.HasIndex("idTrip");

                    b.HasIndex("uploadedById");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TripWise.Models.expense", b =>
                {
                    b.Property<int>("idExpense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idExpense"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("expenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idPoint")
                        .HasColumnType("int");

                    b.Property<int>("idTrip")
                        .HasColumnType("int");

                    b.Property<int>("paidById")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idExpense");

                    b.HasIndex("idPoint");

                    b.HasIndex("idTrip");

                    b.HasIndex("paidById");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TripWise.Models.expenseShare", b =>
                {
                    b.Property<int>("idExpenseShare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idExpenseShare"));

                    b.Property<int>("idExpense")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("shareAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idExpenseShare");

                    b.HasIndex("idExpense");

                    b.HasIndex("idUser");

                    b.ToTable("ExpenseShares");
                });

            modelBuilder.Entity("TripWise.Models.pointOfInterest", b =>
                {
                    b.Property<int>("idPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPoint"));

                    b.Property<int?>("addedById")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("bookingLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idTrip")
                        .HasColumnType("int");

                    b.Property<decimal>("latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("plannedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("plannedTime")
                        .HasColumnType("time");

                    b.HasKey("idPoint");

                    b.HasIndex("addedById");

                    b.HasIndex("idTrip");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("TripWise.Models.role", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRole"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TripWise.Models.trip", b =>
                {
                    b.Property<int>("idTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTrip"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdById")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("totalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idTrip");

                    b.HasIndex("createdById");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TripWise.Models.tripParticipant", b =>
                {
                    b.Property<int>("idTripParticipant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTripParticipant"));

                    b.Property<int>("idTrip")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("joinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("participantRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idTripParticipant");

                    b.HasIndex("idTrip");

                    b.HasIndex("idUser");

                    b.ToTable("TripParticipants");
                });

            modelBuilder.Entity("TripWise.Models.user", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUser"));

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("idRole")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.HasIndex("idRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TripWise.Models.userVote", b =>
                {
                    b.Property<int>("idUserVote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUserVote"));

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<int>("idVoteOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("votedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("idUserVote");

                    b.HasIndex("idUser");

                    b.HasIndex("idVoteOption");

                    b.ToTable("UserVotes");
                });

            modelBuilder.Entity("TripWise.Models.voteOption", b =>
                {
                    b.Property<int>("idVoteOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVoteOption"));

                    b.Property<int>("idVote")
                        .HasColumnType("int");

                    b.Property<string>("optionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("idVoteOption");

                    b.HasIndex("idVote");

                    b.ToTable("VoteOptions");
                });

            modelBuilder.Entity("TripWise.Models.votingSystem", b =>
                {
                    b.Property<int>("IdVote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVote"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("expiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idPoint")
                        .HasColumnType("int");

                    b.Property<int>("idTrip")
                        .HasColumnType("int");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdVote");

                    b.HasIndex("createdById");

                    b.HasIndex("idPoint");

                    b.HasIndex("idTrip");

                    b.ToTable("votingSystems");
                });

            modelBuilder.Entity("TripWise.Models.chatMessage", b =>
                {
                    b.HasOne("TripWise.Models.pointOfInterest", "PointOfInterest")
                        .WithMany()
                        .HasForeignKey("idPoint");

                    b.HasOne("TripWise.Models.trip", "Trip")
                        .WithMany("ChatMessages")
                        .HasForeignKey("idTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.user", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointOfInterest");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripWise.Models.document", b =>
                {
                    b.HasOne("TripWise.Models.trip", "Trip")
                        .WithMany("Documents")
                        .HasForeignKey("idTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.user", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("uploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("TripWise.Models.expense", b =>
                {
                    b.HasOne("TripWise.Models.pointOfInterest", "PointOfInterest")
                        .WithMany("Expenses")
                        .HasForeignKey("idPoint");

                    b.HasOne("TripWise.Models.trip", "Trip")
                        .WithMany("Expenses")
                        .HasForeignKey("idTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.user", "PaidBy")
                        .WithMany("Expenses")
                        .HasForeignKey("paidById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaidBy");

                    b.Navigation("PointOfInterest");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripWise.Models.expenseShare", b =>
                {
                    b.HasOne("TripWise.Models.expense", "Expense")
                        .WithMany("ExpenseShares")
                        .HasForeignKey("idExpense")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.user", "User")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripWise.Models.pointOfInterest", b =>
                {
                    b.HasOne("TripWise.Models.user", "AddedBy")
                        .WithMany()
                        .HasForeignKey("addedById");

                    b.HasOne("TripWise.Models.trip", "Trip")
                        .WithMany("PointOfInterests")
                        .HasForeignKey("idTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripWise.Models.trip", b =>
                {
                    b.HasOne("TripWise.Models.user", "createdBy")
                        .WithMany()
                        .HasForeignKey("createdById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("createdBy");
                });

            modelBuilder.Entity("TripWise.Models.tripParticipant", b =>
                {
                    b.HasOne("TripWise.Models.trip", "Trip")
                        .WithMany("TripParticipants")
                        .HasForeignKey("idTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.user", "User")
                        .WithMany("TripParticipants")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripWise.Models.user", b =>
                {
                    b.HasOne("TripWise.Models.role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TripWise.Models.userVote", b =>
                {
                    b.HasOne("TripWise.Models.user", "User")
                        .WithMany()
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.voteOption", "VoteOption")
                        .WithMany("UserVotes")
                        .HasForeignKey("idVoteOption")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VoteOption");
                });

            modelBuilder.Entity("TripWise.Models.voteOption", b =>
                {
                    b.HasOne("TripWise.Models.votingSystem", "votingSystem")
                        .WithMany("VoteOptions")
                        .HasForeignKey("idVote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("votingSystem");
                });

            modelBuilder.Entity("TripWise.Models.votingSystem", b =>
                {
                    b.HasOne("TripWise.Models.user", "CreatedBy")
                        .WithMany("VotingSystems")
                        .HasForeignKey("createdById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripWise.Models.pointOfInterest", "PointOfInterest")
                        .WithMany()
                        .HasForeignKey("idPoint");

                    b.HasOne("TripWise.Models.trip", "Trip")
                        .WithMany("VotingSystems")
                        .HasForeignKey("idTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PointOfInterest");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripWise.Models.expense", b =>
                {
                    b.Navigation("ExpenseShares");
                });

            modelBuilder.Entity("TripWise.Models.pointOfInterest", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("TripWise.Models.role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripWise.Models.trip", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Documents");

                    b.Navigation("Expenses");

                    b.Navigation("PointOfInterests");

                    b.Navigation("TripParticipants");

                    b.Navigation("VotingSystems");
                });

            modelBuilder.Entity("TripWise.Models.user", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Expenses");

                    b.Navigation("TripParticipants");

                    b.Navigation("VotingSystems");
                });

            modelBuilder.Entity("TripWise.Models.voteOption", b =>
                {
                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("TripWise.Models.votingSystem", b =>
                {
                    b.Navigation("VoteOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
